package com.ridesharing.auth.model;

import com.ridesharing.shared.enums.DriverApprovalStatus;
import com.ridesharing.shared.enums.DriverAvailability;
import com.ridesharing.shared.enums.UserRole;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * The User entity — maps to the "users" table in PostgreSQL.
 * Represents ANY person in the system: Rider, Driver, or Admin.
 *
 * WHY one User table for all roles?
 *   - A person logs in the same way regardless of role (email + password)
 *   - Riders and Drivers share common fields (name, email, phone)
 *   - Role-specific data (vehicle, documents) lives in separate tables
 *   - Simpler auth logic: one table, one repository, one JWT flow
 *
 * @Entity tells JPA: "This class is a database table"
 * @Table(name = "users") tells JPA: "The table is called 'users'"
 *   (we don't use "user" because it's a reserved keyword in PostgreSQL)
 */
@Entity
@Table(name = "users")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Primary key — auto-generated by PostgreSQL.
     * @Id marks this as the primary key.
     * @GeneratedValue(IDENTITY) tells PostgreSQL to auto-increment: 1, 2, 3, ...
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Full name of the user. Cannot be null.
     * @Column(nullable = false) adds a NOT NULL constraint in the database.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Email address — used for login. Must be unique across all users.
     * @Column(unique = true) adds a UNIQUE constraint in the database.
     * If two users try to register with the same email, PostgreSQL rejects the second one.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * BCrypt-hashed password. NEVER stores plain text.
     * Example stored value: "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy"
     * Even we (the developers) cannot read the original password from this.
     */
    @Column(nullable = false)
    private String password;

    /**
     * Phone number for contact and OTP (future feature).
     */
    @Column(nullable = false)
    private String phone;

    /**
     * Role determines what this user can do in the system.
     * @Enumerated(STRING) stores the enum value as text in the database ("RIDER", "DRIVER", "ADMIN")
     * instead of a number (0, 1, 2). Text is more readable and doesn't break if enum order changes.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserRole role;

    /**
     * Whether this account is active. Admin can set this to false to suspend a user.
     * @Builder.Default ensures this defaults to true when using the Builder pattern.
     */
    @Builder.Default
    @Column(nullable = false)
    private boolean active = true;

    /**
     * Driver-only: tracks whether admin has approved this driver.
     * NULL for riders and admins. PENDING → APPROVED / REJECTED for drivers.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "approval_status")
    private DriverApprovalStatus approvalStatus;

    /**
     * Driver-only: tracks whether driver is currently accepting rides.
     * NULL for riders and admins. ONLINE / OFFLINE / BUSY for drivers.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "availability")
    private DriverAvailability availability;

    @Column(name = "average_rating", precision = 3, scale = 2)
    @Builder.Default
    private java.math.BigDecimal averageRating = java.math.BigDecimal.ZERO;

    @Column(name = "total_ratings")
    @Builder.Default
    private Integer totalRatings = 0;

    /**
     * When this user was created. Set automatically, never changes.
     * Useful for analytics ("how many users registered this month?")
     * and debugging ("when did this user join?").
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * When this user was last modified. Updated on every change.
     * Useful for detecting stale data and audit trails.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Automatically set timestamps before first save.
     * @PrePersist is a JPA lifecycle callback — runs BEFORE the INSERT SQL.
     */
    @jakarta.persistence.PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Automatically update the timestamp before every update.
     * @PreUpdate is a JPA lifecycle callback — runs BEFORE the UPDATE SQL.
     */
    @jakarta.persistence.PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
